<p class="context_population"><span class="context_label" data-i18n="population"></span><span class="context_value">{{ population }}</span></p>
<p class="context_students"><span class="context_label" data-i18n="students"></span><span class="context_value">{{ students }}</span></p>
<p class="context_ground_surface"><span class="context_label" data-i18n="ground_surface"></span><span class="context_value">{{ ground_surface }}</span></p>
<p class="context_socioeconomic_index"><span class="context_label" data-i18n="socioeconomic_index"></span><span class="context_value">{{ socioeconomic_index }}</span></p>
