<span class="entity">{{muni.attributes.name}}</span>
<span class="selected_nodes_count">{{#state}}{{state.selected.length}}{{/state}}{{^state}}0{{/state}}</span>
<p class="legend_item_title">{{title}}</p>
<div class="legend_item_buttons transitioned">
    <span class="legend_item_delete">X</span><span
    class="legend_item_edit">E</span><span
    class="legend_item_duplicate">D</span><span
    class="legend_item_color">C</span>
</div>

