<span class="entity">{{muni.attributes.name}}</span>
<p class="legend_item_count">
    <span class="selected_nodes_count">{{#state}}{{state.selected.length}}{{/state}}{{^state}}0{{/state}}</span>
    selected items
</p>
<p class="legend_item_title">{{title}}</p>
<span class="legend_item_remove"></span>
<div class="legend_item_buttons transitioned">
    <span  class="legend_item_duplicate"></span><span
    class="legend_item_edit"></span><span
    class="legend_item_delete"></span>
</div>

